<script type="text/javascript">
<?php 
switch($this->result) {
	case "showTitleSuccess":
		echo "showTitleSuccess();";
		break;
	case "showTitleError":
		echo "showTitleError();";
		break;
				
	case "showMetaSuccess":
		echo "showMetaSuccess();";
		break;
	case "showMetaError":
		echo "showMetaError();";
		break;	

	case "showJavascriptSuccess":
		echo "showJavascriptSuccess();";
		break;
	case "showJavascriptError":
		echo "showJavascriptError();";
		break;

	case "showCssSuccess":
		echo "showCssSuccess();";
		break;
	case "showCssError":
		echo "showCssError();";
		break;		

	case "showAclSuccess":
		echo "showAclSuccess();";
		break;
	case "showAclError":
		echo "showAclError();";
		break;	

	case "showNavigationSuccess":
		echo "showNavigationSuccess();";
		break;
	case "showNavigationError":
		echo "showNavigationError();";
		break;			
}
?>
</script>
