<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />

		<?php echo $this->headTitle();?>
		<link type="text/css" rel="stylesheet" media="all" href="/css/maerdo/reset.css" />        
        <link type="text/css" rel="stylesheet" media="all" href="/css/maerdo/header.css" />
        <link type="text/css" rel="stylesheet" media="all" href="/css/maerdo/nav.css" />
        <link type="text/css" rel="stylesheet" media="all" href="/css/maerdo/sidebar.css" />
        <link type="text/css" rel="stylesheet" media="all" href="/css/maerdo/footer.css" />
        <link type="text/css" rel="stylesheet" media="all" href="/css/maerdo/styles.css" />
        <link type="text/css" rel="stylesheet" media="all" href="/css/jquery-ui/smoothness/jquery.ui.all.css" />        
        <?php echo $this->headLink();?>
        
        

        <script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>
		<script type="text/javascript" src="/js/jquery-ui/jquery-ui-1.8.9.js"></script>
       

        <?php echo $this->headScript() ?>
    </head>

    <body>
        	<?php if($this->layout()->reportMessage==true):?>
            <div style='font-weight:bold;width:100%;background-color:#dedede;text-align:center;'>
            	<br />
            	<?php echo $this->translate('<a href="http://bugstracker.maerdo.com">You use a beta version. Report your bugs on http://bugstracker.maerdo.com. Thanks</a>')?>
            	<br /><br />
            </div>	
            <?php endif;?> 
        <div id="header">   
            <div class="header-top tr">
                <a href="/maerdo/logout">Logout</a></p>
            </div>

            <div class="header-middle">
                <!-- Start Nav -->
                <?php echo $this->render('snippets/top_menu.phtml');?>                                
                <!-- End Nav -->
                <img id="logo" src="/images/logo.png" alt="Admin Theme" />
                <br class="cl" />
            </div>
            <div class="header-bottom">
                <ul id="breadcrumbs">
                    <li><a href="#">Maerdo</a> »</li>
                    <li><a href="#">Home</a></li>
                </ul>
            </div>
        </div>
        <div id="page-wrapper">
            <div class="page">
                <!-- Start Sidebar -->
                <div id="sidebar">
                   <?php echo $this->render($this->layout()->sidebar_file);?>           
                </div>
                <!-- End Sidebar  -->
                
                <!-- Star Page Content  -->
                <div id="page-content">
                    <!-- Start Page Header -->
                    <?php echo $this->layout()->content;?>                   
                    <!-- End Page Header -->
                </div>
                 <!-- End Page Content  -->
                 <div class="cleaner"></div>
            </div>
            <br class="cl" />
        </div>
        <!-- Start Footer -->
        <div class="footer">
            Copyright ©2010, MAERDO.
        </div>
        <!-- End Footer -->
    </body>
</html>
