<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />

		<?php echo $this->headTitle();?>
		     
        <?php echo $this->headLink();?>
        
        <script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>
		<script type="text/javascript" src="/js/jquery-ui/jquery-ui-1.8.9.js"></script>
       
        <?php echo $this->headScript() ?>
    </head>

    <body>
		<?php echo $this->layout()->content;?>
    </body>
</html>
