<div id="page-header">
	<h1><?php echo $this->translate('Authentification')?></h1>
</div>

<?php if($this->notification_error!=NULL):?>
<div class='notification_error px700'>
	<?php if($this->notification_error=='update_auth_error'):?>
	<div><?php echo $this->translate('An error has occured when trying to update auth configuration or item was not modified.');?><br /></div>
	<?php endif;?>
</div>
<br /><br />
<?php endif;?>


<?php if($this->notification_success!=NULL):?>
<div class='notification_success px700'>
	<?php if($this->notification_success=='update_auth_success'):?>
	<div><?php echo $this->translate('The authentification configuration has been update.');?><br /></div>
	<?php endif;?>
</div>	
<br /><br />
<?php endif;?>

<?php echo $this->translate("Select a module")?> :
<select id='select_module' class="px200">
	<option value="null">-- Select a module --</option>
	<?php 
	foreach($this->modules as $module):
		$selected="";if($module->id==$this->module_id) $selected='selected="selected"';
		echo "<option $selected value='".$module->id."'>".$module->name."</option>";
	endforeach;
	?>
</select>
<br /><br />
<?php if($this->module_id!=null): ?>
<form id="form_auth" action='/maerdo/component/auth' method='post'>
<h2><?echo $this->translate('Database configuration');?></h2>
<input type="hidden" name="module_id" value="<?=$this->module_id?>" />
<input type="hidden" name="form_action" value="update_auth" />


<table>
	<tr>
		<td class='px200'><?echo $this->translate('Database')?></td>
		<td class='px200'>
			<select class='px200' name='auth[database_name]'>	
				<?php foreach($this->databases as $database):?>
					<option value="<?=$database['name']?>"><?=$database['name']?></option>
				<?php endforeach;?>		
			</select>
		</td>
	</tr>
	<tr>
		<td class='px200'><?echo $this->translate('Table')?> :</td>
		<td class='px200'>
			<input id='auth_table' type="text" value="<?=$this->authconfiguration['table']?>" class="px200" name="auth[table]" />
		</td>
	</tr>
	<tr>
		<td class='px200'><?echo $this->translate('Username field')?> :</td>
		<td class='px200'>
			<input id='auth_username_field' type="text" value="<?=$this->authconfiguration['username_field']?>" class="px200" name="auth[username_field]" />
		</td>
	</tr>
	<tr>
		<td class='px200'><?echo $this->translate('Password field')?> :</td>
		<td class='px200'>
			<input id='auth_password_field' type="text" value="<?=$this->authconfiguration['password_field']?>" class="px200" name="auth[password_field]" />
		</td>
	</tr>
	<tr>
		<td class='px200'><?echo $this->translate('Role field')?> :</td>
		<td class='px200'>
			<input id='auth_role_field' type="text" value="<?=$this->authconfiguration['role_field']?>" class="px200" name="auth[role_field]" />
		</td>
	</tr>	
	
	<tr>
		<td colspan='2'><h2><?echo $this->translate('Redirection URL after authentification')?> :</h2></td>	
	</tr>	
	<?php foreach($this->aclRoles as $role):?>
	<tr>
		<td class='px200'><?echo $role->role?> :</td>
		<td class='px200'>
			<input type="text" value="<?=$this->authconfiguration['redirection_role'][$role->role]?>" class="auth_url px200" name="auth[redirection][<?echo $role->role?>]" />
		</td>
	</tr>		
	<?php endforeach;?>		
	<tr>
		<td colspan='2'>
			<br />
			<img id='img_submit_form' class="pointer fright" src='/tools/button/white/Update authentification configuation/000000/arial/10/edit.gif/0/0' />
		</td>	
	</tr>		
</table>
			
</form>
<?php endif;?>