<div id="page-header">
	<h1><?php echo $this->translate('Cache')?></h1>
</div>

<?php if($this->notification_error!=NULL):?>
<div class='notification_error px700'>
	<?php if($this->notification_error=='add_cache_error'):?>
	<div><?php echo $this->translate('An error has occured when trying to add the cache.');?><br /></div>
	<?php endif;?>
	<?php if($this->notification_error=='delete_cache_error'):?>
	<div><?php echo $this->translate('An error has occured when trying to delete the cache.');?><br /></div>
	<?php endif;?>	
</div>
<?php endif;?>	

<?php if($this->notification_success!=NULL):?>
<div class='notification_success px700'>
	<?php if($this->notification_success=='add_cache_success'):?>
	<div><?php echo $this->translate('The cache has been created.');?><br /></div>
	<?php endif;?>	
	<?php if($this->notification_success=='delete_cache_success'):?>
	<div><?php echo $this->translate('The cache has been deleted.');?><br /></div>
	<?php endif;?>		
</div>
<br />
<?php endif;?>
<a href='#' onclick="$('#cache_form').toggle()"><img class='pr t3 mr5' src='/images/icons/add.png'></>Add a cache</a>
<br /><br />
<table class="px400">
	<tr class="bggrey bold">
		<td><?php echo $this->translate('Name')?></td>
		<td><?php echo $this->translate('Frontend Type')?></td>
		<td><?php echo $this->translate('Backend support')?></td>
		<td><?php echo $this->translate('Actions')?></td>
	</tr>
	<?php foreach($this->caches as $cache):?>
	<tr>
		<td><?=$cache->name?></td>
		<td><?=$cache->type?></td>
		<td><?=$cache->backend_type?></td>
		<td>
			<a href='/maerdo/component/cache/?form_action=update_form&id=<?=$cache->id?>'><img src='/images/icons/edit.gif' alt='edit' /></a>
			<a href='/maerdo/component/cache/?form_action=delete&id=<?=$cache->id?>'><img src='/images/icons/delete.gif' alt='delete' /></a>			
		</td>
	</tr>	
	<?php endforeach;?>
</table>
<div id='cache_form' class='hidden'>
<form id="form_cache" action='/maerdo/component/cache/' method="post">
	<input type="hidden" name="form_action" value="add_cache" />
	<br /><br /><br />
	<table class="px400">
		<tr>
			<td class="px200">Name :</td>
			<td>
				<input type="text" name="cache[name]" />
			</td>
		</tr>	
		<tr>
			<td class="px200">Cache Type :</td>
			<td>
				<select name="cache[frontend_type]" class="px200">
					<option value="Core">Core</option>
					<option value="File">File</option>
					<option value="Class">Class</option>
					<option value="Function">Function</option>
					<option value="Page">Page</option>
				</select>
			</td>
		</tr>
	</table>		
	<br /><br />	
	<h2><?php echo $this->translate('Backend')?> :</h2>
	<table class="px400">
		<tr>
			<td class="px200">Support :</td>
			<td>
				<select class="px200" name="cache[backend_type]" id='cache_backend_type'>
					<option value="apc">APC</option>						
					<option value="file">File</option>
				</select>
			</td>
		</tr>
		<tr class="hidden backend_file backend_type">
			<td><?php echo $this->translate('Cache dir')?> :</td>
			<td>
				<input type="text" name="cache[backend][file][cache_dir]" />
			</td>
		</tr>	
		<tr class="hidden backend_file backend_type">
			<td> <?php echo $this->translate('File locking')?>:</td>
			<td>
				<select name="cache[backend][file][file_locking]" class="px200">
					<option value="true">True</option>
					<option value="false">False</option>
				</select>
			</td>
		</tr>

		<tr class="hidden backend_file backend_type">
			<td><?php echo $this->translate('Read control')?> :</td>
			<td>
				<select name="cache[backend][file][read_control]" class="px200">
					<option value="md5">md5</option>
					<option value="crc32">crc32</option>
					<option value="adler32">adler32</option>
					<option value="strlen">strlen</option>
				</select>
			</td>
		</tr>		
		<tr class="hidden backend_file backend_type">
			<td> <?php echo $this->translate('read_control_type')?>:</td>
			<td>
				<select name="cache[backend][file][read_control_type]" class="px200">
					<option value="true">True</option>
					<option value="false">False</option>
				</select>
			</td>
		</tr>		
		<tr class="hidden backend_file backend_type">
			<td><?php echo $this->translate('Hash directory level')?> :</td>
			<td>
				<input type="text" name="cache[backend][file][hashed_directory_level]" />
			</td>
		</tr>		
		<tr class="hidden backend_file backend_type">
			<td><?php echo $this->translate('Hash directory umask')?> :</td>
			<td>
				<input type="cache[backend][file][hashed_directory_umask]" />
			</td>
		</tr>		
		<tr class="hidden backend_file backend_type">
			<td><?php echo $this->translate('Metatadatas array max size')?> :</td>
			<td>
				<input type="text" name="cache[backend][file][metatadatas_array_max_size]" />
			</td>
		</tr>		
		
		
			
		<tr class="hidden backend_sqlite backend_type">
			<td><?php echo $this->translate('Cache db complete path')?> :</td>
			<td>
				<input type="cache[backend][sqlite][cache_db_complete_path]" />
			</td>
		</tr>	
		<tr class="hidden backend_sqlite backend_type">
			<td><?php echo $this->translate('Automatic vacuum factor')?> :</td>
			<td>
				<input type="cache[backend][sqlite][automatic_vacuum_factor]" />
			</td>
		</tr>		
		
	</table>	
	<br /><br />	
	<h2><?php echo $this->translate('Frontend')?> :</h2>
	<table class="px400">
		<tr>
			<td class="px200"><?php echo $this->translate('Writecontroler')?> :</td>
			<td>
				<select name="cache[frontend][writecontrol]">
					<option value="false">False</option>
					<option value="true">True</option>				
				</select>
			</td>
		</tr>	
		<tr>
			<td><?php echo $this->translate('Caching')?> :</td>
			<td>
				<select name="cache[frontend][caching]">
					<option value="false">False</option>		
					<option value="true">True</option>			
				</select>
			</td>
		</tr>			
		<tr>
			<td><?php echo $this->translate('Cache id prefix')?> :</td>
			<td>
				<input type="text" name="cache[frontend][cache_id_prefix]" value="" />
			</td>
		</tr>				
		<tr>
			<td><?php echo $this->translate('Automatic serialization')?> :</td>
			<td>
				<select name="cache[frontend][automatic_serialisation]">
					<option value="file">False</option>	
					<option value="apc">True</option>							
				</select>
			</td>
		</tr>
		<tr>
			<td><?php echo $this->translate('Automatic cleaning factor')?> :</td>
			<td>
				<select name="cache[frontend][automatic_cleaning_factor]">
					<option value="file">False</option>	
					<option value="apc">True</option>						
				</select>
			</td>
		</tr>		
		
		<tr>
			<td><?php echo $this->translate('Lifetime')?> :</td>
			<td>
				<input type="text" name="cache[frontend][lifetime]" value="3600" />
			</td>
		</tr>	
	
		<tr>
			<td><?php echo $this->translate('Logging')?> :</td>
			<td>
				<select name="cache[frontend][logging]">
					<option value="false">False</option>
					<option value="true">True</option>								
				</select>
			</td>
		</tr>	
		
		<tr>
			<td><?php echo $this->translate('Logger')?> :</td>
			<td>
				<input type="text" name="cache[frontend][logger]" />
			</td>
		</tr>				
	
		<tr>
			<td colspan="2">
				<br /><br />
				<img  id='img_add_submit' class="fright pointer" alt='Add Cache configuration' src='/tools/button/white/Add cache configuration/000000/arial/10/edit.gif/0/0' />
			</td>
		</tr>			
	</table>		
	<br />
</form>	
</div>
