
                    <span class="ul-header"><a id="toggle-pagesnav" href="#" name="toggle-pagesnav"><?php echo $this->translate('Parameters');?></a></span>
                    <ul id="pagesnav">
                        <li><a class="icn_add_pages" href="/maerdo/parameters">Configuration</a></li>
                    </ul>
                    
                    <span class="ul-header">Statistics</span>
                    <ul>
						<li>Pages: <?php echo $this->sidebarCountPage?> </li>
                        <li>Modules: <?php echo $this->sidebarCountModule?> </li>
                        <li>Controller: <?php echo $this->sidebarCountController?> </li>
                        <li>Action: <?php echo $this->sidebarCountAction?> </li>                       
                    </ul>
              