
                    <span class="ul-header"><a id="toggle-pagesnav" href="#" name="toggle-pagesnav">Content</a></span>
                    <ul id="pagesnav">
                        <li><a class="icn_manage_pages" href="/maerdeo/pages/">Pages list</a></li>
                    </ul>
                    
                    <span class="ul-header">Statistics</span>
                    <ul>
						<li>Pages: <?=$this->sidebarCountPage?> </li>
                        <li>Modules: <?=$this->sidebarCountModule?> </li>
                        <li>Controller: <?=$this->sidebarCountController?> </li>
                        <li>Action: <?=$this->sidebarCountAction?> </li>                       
                    </ul>
        