<div id="page-header">
	<h1><?php echo  $this->translate('Edit a form')?></h1>
</div>

<?php if($this->notification_error!=NULL):?>
<div class='notification_error px700'>
	<?php if($this->notification_error=='delete_field_error'):?>
	<div><?php echo  $this->translate('An error has occured when trying to delete the field.');?><br /></div>
	<?php endif;?>
	<?php if($this->notification_error=='add_field_error'):?>
	<div><?php echo  $this->translate('An error has occured when trying to add the field.');?><br /></div>
	<?php endif;?>	
	<?php if($this->notification_error=='update_form_error'):?>
	<div><?php echo  $this->translate('An error has occured when trying to update the form.');?><br /></div>
	<?php endif;?>		
</div>
<?php endif;?>	

<?php if($this->notification_success!=NULL):?>
<div class='notification_success px700'>
	<?php if($this->notification_success=='delete_field_success'):?>
	<div><?php echo  $this->translate('The field has been deleted.');?><br /></div>
	<?php endif;?>
	<?php if($this->notification_success=='add_field_success'):?>
	<div><?php echo  $this->translate('The field has been added.');?><br /></div>
	<?php endif;?>	
	<?php if($this->notification_success=='update_form_success'):?>
	<div><?php echo  $this->translate('The form has been updated.');?><br /></div>
	<?php endif;?>	
</div>
<?php endif;?>	
<br /><br />
<a href='/maerdo/component/forms/'>- Return to forms list</a>
<br />
<br />
<h2 ><?php echo  $this->translate('Parameters');?></h2>
<div id="parameters">

	<div id='form_error' class='notification_error hidden px700'>
		<div><?php echo  $this->translate('All field must be setted to valid form.');?><br /></div>
	</div>
	<br />
	<form id='form' action='/maerdo/component/forms/edit/<?php echo  $this->form_id?>' method='post'>
		<input type="hidden" name="form_action" value="update_form" />
		<table>
			<tr>
				<td><?php echo  $this->translate('Form name')?> :</td>
				<td><input id="form_name" type="text" value="<?php echo $this->form_info->name?>" name="form[name]" class="px200" /></td>
			</tr>
			<tr>
				<td><?php echo  $this->translate('Template')?> :</td>
				<td>
					<select id="form_template" name="form[template]" class="px200">
						<?php 
						if(is_array($this->templates)) {
							foreach($this->templates as $file):
								$selected="";if($this->form_info->template==$file)  $selected='selected="selected"';							
								echo "<option $selected value='$file'>$file</option>";
							endforeach;			
						}
						?>
					</select>
				</td>
			</tr>					
			<tr>
				<td><?php echo  $this->translate('Action URL')?> :</td>
				<td><input id="form_actionurl" type="text" value="<?php echo $this->form_info->action?>" name="form[action_url]" class="px200" /></td>
			</tr>	
			<tr>
				<td><?php echo  $this->translate('Method')?> :</td>
				<td>
					<select name="form[method]" class="px200">
						
						<option <?php if($this->form_info->method=="post") echo "selected='selected'"?> value="post">POST</option>
						<option <?php if($this->form_info->method=="get") echo "selected='selected'"?>value="get">GET</option>
					</select>
				</td>
			</tr>							
		</table>
		<br />
		<img id='img_add_submit_form' class="ml185" src='/tools/button/white/Update form/000000/arial/10/edit.gif/0/0' />	
	</form>
</div>

<h2><?php echo  $this->translate('Fields');?></h2>
<h3><?php echo  $this->translate('Add a field')?></h3>
<div id='form_add_field_div'>
	<form  id='form_add_field' action='/maerdo/component/forms/edit/<?php echo $this->form_id?>' method='post'>
	<input type="hidden" name="form_action" value="add_field" />
	<div id='form_field_error' class='notification_error hidden px700'>
		<div><?php echo  $this->translate('All field must be setted to valid form.');?><br /></div>
	</div>	
	<br />
	<table>
		<tr>
			<td><?php echo  $this->translate('Field type')?> :</td>
			<td>
				<select id='field_type' name="field_type" class="px200">
					<?php 
					if(is_array($this->fieldTypes)):
						foreach($this->fieldTypes as $type):?>
							<option value='<?php echo $type->type?>'><?php echo $type->type?></option>						
					<?php 
						endforeach;
					endif;
					?>	
				</select>
			</td>
		</tr>
		<tr>
			<td><?php echo  $this->translate('Field name')?> :</td>
			<td><input id="field_name" type="text" name="field_name" value="" class="px200" /></td>
		</tr>
		<tr>
			<td colspan="2">
				<img id='img_add_field_submit_form' class="ml185" src='/tools/button/white/Add field/000000/arial/10/edit.gif/0/0' />
			</td>
		</tr>					
	</table>
	</form>
</div>		
<br /><br />
<h3><?php echo  $this->translate('Fields list')?></h3>
<table class="px400">
	<tr class="bggrey">
		<td>Name</td>
		<td>Type</td>		
		<td>Action</td>
	</tr>
		
	<?php 
		if(is_array($this->fields)):
			foreach($this->fields as $field):?>
				<tr>
					<td><?php echo $field->name?></td>
					<td><?php echo $field->type?></td>					
					<td>
						<a href='/maerdo/component/forms/edit/field/<?php echo $field->id?>'><img src='/images/icons/edit.gif' alt='Edit' /></a>
						<a href='/maerdo/component/forms/edit/<?php echo $this->form_id?>/?form_action=delete_field&field_id=<?php echo $field->id?>'><img src='/images/icons/delete.gif' alt='delete' />
					</td>
				</tr>					
		<?php 
			endforeach;
		endif;
		?>		
</table>					
