<div id="page-header">
	<h1><?php echo $this->translate('Edit a form')?></h1>
</div>

<?php if($this->notification_error!=NULL):?>
<div class='notification_error px700'>
	<?php if($this->notification_error=='delete_field_error'):?>
	<div><?php echo $this->translate('An error has occured when trying to delete the field.');?><br /></div>
	<?php endif;?>
	<?php if($this->notification_error=='add_field_error'):?>
	<div><?php echo $this->translate('An error has occured when trying to add the field.');?><br /></div>
	<?php endif;?>	
</div>
<?php endif;?>	

<?php if($this->notification_success!=NULL):?>
<div class='notification_success px700'>
	<?php if($this->notification_success=='delete_field_success'):?>
	<div><?php echo $this->translate('The field has been deleted.');?><br /></div>
	<?php endif;?>
	<?php if($this->notification_success=='add_field_success'):?>
	<div><?php echo $this->translate('The field has been added.');?><br /></div>
	<?php endif;?>	
</div>
<?php endif;?>	
<br /><br />
<h2 ><?php echo $this->translate('Parameters');?></h2>
<div id="parameters">
	<form id='form_add' action='/maerdo/component/forms/' method='post'>
		<input type="hidden" name="form_action" value="add_form" />
		<table>
			<tr>
				<td><?php echo $this->translate('Form name')?> :</td>
				<td><input type="text" name="form[name]" class="px200" /></td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Template')?> :</td>
				<td>
					<select name="form[template]" class="px200">
						<?php 
						if(is_array($this->templates)) {
							foreach($this->templates as $file):
								echo "<option value='$file'>$file</option>";
							endforeach;			
						}
						?>
					</select>
				</td>
			</tr>					
			<tr>
				<td><?php echo $this->translate('Action URL')?> :</td>
				<td><input type="text" name="form[action_url]" class="px200" /></td>
			</tr>	
			<tr>
				<td><?php echo $this->translate('Method')?> :</td>
				<td>
					<select name="form[method]" class="px200">
						<option value="post">POST</option>
						<option value="get">GET</option>
					</select>
				</td>
			</tr>							
		</table>
		<br />
		<img id='img_add_submit_form' class="ml185" src='/tools/button/white/Update form/000000/arial/10/edit.gif/0/0' />	
	</form>
</div>

<h2><?php echo $this->translate('Fields');?></h2>
<a href='#' onclick='$("#form_add_field_div").toggle()'><img src='/images/icons/add.png' class='pr t3 mr5' alt='Add' /><?php echo $this->translate('Add a field')?></a>
<div id='form_add_field_div' class='hidden'>
	<form id='form_add_field' action='/maerdo/component/forms/edit/<?=$this->form_id?>' method='post'>
	<input type="hidden" name="form_action" value="add_field" />
	<table>
		<tr>
			<td><?php echo $this->translate('Field type')?> :</td>
			<td>
				<select name="field_type" class="px200">
					<?php 
					if(is_array($this->fieldTypes)):
						foreach($this->fieldTypes as $type):?>
							<option value='<?=$type->type?>'><?=$type->type?></option>						
					<?php 
						endforeach;
					endif;
					?>	
				</select>
			</td>
		</tr>
		<tr>
			<td><?php echo $this->translate('Field name')?> :</td>
			<td><input type="text" name="field_name" class="px200" /></td>
		</tr>
		<tr>
			<td colspan="2">
				<img id='img_add_field_submit_form' class="ml185" src='/tools/button/white/Add field/000000/arial/10/edit.gif/0/0' />
			</td>
		</tr>					
	</table>
	</form>
</div>		
<br /><br />
<table class="px400">
	<tr class="bggrey">
		<td>Name</td>
		<td>Type</td>		
		<td>Action</td>
	</tr>
		
	<?php 
		if(is_array($this->fields)):
			foreach($this->fields as $field):?>
				<tr>
					<td><?=$field->name?></td>
					<td><?=$field->type?></td>					
					<td>
						<a href='/maerdo/component/forms/edit/field/<?=$field->id?>'><img src='/images/icons/edit.gif' alt='Edit' /></a>
						<a href='/maerdo/component/forms/edit/<?=$this->form_id?>/?form_action=delete_field&field_id=<?=$field->id?>'><img src='/images/icons/delete.gif' alt='delete' />
					</td>
				</tr>					
		<?php 
			endforeach;
		endif;
		?>		
</table>					
