<div id="page-header">
	<h1><?php echo $this->translate('Edit a validator configuration')?></h1>
</div>

<?php if($this->notification_error!=NULL):?>
<div class='notification_error px900'>
	<?php if($this->notification_error=='updateOptions_error'):?>
	<div><?php echo $this->translate('An error has occured when trying to update validator options.');?><br /></div>
	<?php endif;?>
			
</div>
<br /><br />
<?php endif;?>


<?php if($this->notification_success!=NULL):?>
<div class='notification_success px900'>
	<?php if($this->notification_success=='updateOptions_success'):?>
	<div><?php echo $this->translate('The validator options has been updated.');?><br /></div>
	<?php endif;?>
</div>
<br /><br />
<?php endif;?>	
	
<a href='/maerdo/component/forms/edit/field/<?=$this->field_id?>/'>> <?php echo $this->translate('Return to field form')?></a><br />
<br /><br />
<div id="tabs" class="px900">
    <ul class="px900">		
        <li><a href="#tabs-1"><?php echo $this->translate('Options')?></a></li>
        <li><a href="#tabs-2"><?php echo $this->translate('Messages')?></a></li>
    </ul>
    <div id="tabs-1">
         <h1>Options</h1>
         <form id='form_validators' action='/maerdo/component/forms/edit/field/<?=$this->field_id?>/validator/<?=$this->validator_id?>' method='post'>
         <input type="hidden" name="form_action" value="update_validatoroptions" />
		<?php echo $this->translate('Add this option')?> :
         <select  id='validator_option' name="select_option">
         	<?php foreach($this->validator_options_list as $option):?>
         		<option value='<?=$option?>'><?=$option?></option>
         	<?php endforeach;?>
         	<option value='other'><?php echo $this->translate('Other');?></option>
         </select>	
         <input onclick="addOption()" type="button"  value="<?php echo $this->translate('Add')?>" /> 
         <br /><br />
         <br />
         <table name="table_option" class="px450" id='table_option'>
         	<tr class="bggrey bold">
         		<td class="px200"><?php echo $this->translate('Option')?></td>
         		<td class="px300"><?php echo $this->translate('Value')?></td>
         		<td><?php echo $this->translate('Delete')?></td>
         	</tr>  
         	<?php 
         		$i=0;
         		foreach($this->validator_options as $option):?>
				<tr id='table_option_<?=$i?>'>
					<?php if($option->option=="other") :?>
						<td class='px200'><input type='text' name='option[<?=$i?>][option]' value='' /></td>
					<?php else: ?> 
						<td class='px200'><input type='hidden' id='option_<?=$i?>' name='option[<?=$i?>][option]' value='<?=$option->option?>' /><?=$option->option?></td>
					<?php endif;?>
					<td class='px300'><input type='text' class='px300' name='option[<?=$i?>][value]' value='<?=$option->value?>' /></td>
					<td><a href='#table_option' onclick='deleteOption("<?=$i?>")'><img class='pr t3' src='/images/icons/delete.gif' /></a></td>
				</tr>
		 		<?php 
		 		$i++;
		 		endforeach;?>       	
         </table>
         <br /><br />
         <img id='img_validator_submit_form' class="ml300" src='/tools/button/white/Update validators/000000/arial/10/edit.gif/0/0' />		 
    </div>
    <div id="tabs-2">

    </div>
</div>    