
<div id="page-header">
	<h1><?php echo  ($this->translate('Edit module'));?> "<?php echo $this->module_details['name']?>"</h1>
</div>

<?php if($this->notification_error!=NULL):?>
<div class='notification_error px700'>
	<?php if($this->notification_error=='controller_already_exist'):?>
	<div><?php echo  $this->translate('A controller with this name already exist.');?><br /></div>
	<?php endif;?>
	
	<?php if($this->notification_error=='add_controller_error'):?>
	<div><?php echo  $this->translate('An error has occured when trying to add controller.');?><br /></div>
	<?php endif;?>	
	
	<?php if($this->notification_error=='action_already_exist'):?>
	<div><?php echo  $this->translate('An action with this name already exist.');?><br /></div>
	<?php endif;?>
	
	<?php if($this->notification_error=='add_action_error'):?>
	<div><?php echo  $this->translate('An error has occured when trying to add the action.');?><br /></div>
	<?php endif;?>	
	
	<?php if($this->notification_error=='delete_controller_error'):?>
	<div><?php echo  $this->translate('An error has occured when trying to delete the controller.');?><br /></div>
	<?php endif;?>
	
	<?php if($this->notification_error=='delete_action_error'):?>
	<div><?php echo  $this->translate('An error has occured when trying to delete the action.');?><br /></div>
	<?php endif;?>			
</div>
<br />
<?php endif;?>

<?php if($this->notification_success!=NULL):?>
<div class='notification_success px700'>
	<?php if($this->notification_success=='controller_has_been_added'):?>
	<div><?php echo  $this->translate('Controller has been added.');?><br /></div>
	<?php endif;?>	

	<?php if($this->notification_success=='action_has_been_added'):?>
	<div><?php echo  $this->translate('Action has been added.');?><br /></div>
	<?php endif;?>	

	<?php if($this->notification_success=='controller_has_been_deleted'):?>
	<div><?php echo  $this->translate('Controller has been deleted.');?><br /></div>
	<?php endif;?>	

	<?php if($this->notification_success=='action_has_been_deleted'):?>
	<div><?php echo  $this->translate('Action has been deleted.');?><br /></div>
	<?php endif;?>		
</div>
<br />
<?php endif;?>



<h2>Contents</h2>
<a href='#' onclick='showControllerForm()'><img src='/images/icons/add.png' alt='Add' class="pr t3 mr5"/>Add a controller</a><br />
<a href='#' onclick='showActionForm()'><img src='/images/icons/add.png' alt='Add' class='pr t3 mr5'/>Add an action</a><br />
<br />
<img src='/images/icons/folder.png' alt='Controller' class="pr t3 mr5"/> Controller
<img src='/images/icons/page_white_text_width.png' class='pr t3 mr5 ml20' /> Action
<br />
<br />
<table>
	<tr class='bggrey bold'>
		<td class="px300"><?php echo  $this->translate('Name')?></td>
		<td class="px400"><?php echo  $this->translate('Description')?></td>
		<td class="px20"><?php echo  $this->translate('Action')?></td>
	</tr>
	<?php 
	$class='';
	if(is_array($this->module_details['controllers'])) {
		foreach($this->module_details['controllers'] as $controller):
			($class=='') ? $class='bggreylight' : $class='';
		?>
			<tr class='<?php echo $class?>'>
				<td class="px300"><img src='/images/icons/folder.png' alt='Controller' class="pr t3 mr5"/><?php echo $controller['name']?></td>
				<td class="px400"><?php echo $controller['description']?></td>
				<td class="px20">
					<a href='/maerdo/modules/edit/<?php echo  $this->module_details['id']?>?form_action=delete_controller&controller_id=<?php echo $controller['id']?>'><img src='/images/icons/delete.gif' alt='Delete' /></a>
				</td>
			</tr>		
			<?php 
			if(count($controller['actions'])>0):
				if(is_array($controller['actions'])) {			
					foreach($controller['actions'] as $action):
						($class=='') ? $class='bggreylight' : $class='';
						?>	
						<tr class='<?php echo $class?>'>
							<td class="px200">
								<div class='ml20'>				
									<img src='/images/icons/page_white_text_width.png' class='pr t3 mr5' /><?php echo $action['name']?><br />				
								</div>
							</td>
							<td><?php echo $action['description']?></td>
							<td class='px20'>
								<a href='/maerdo/modules/edit/<?php echo  $this->module_details['id']?>?form_action=delete_action&action_id=<?php echo $action['id']?>'><img src='/images/icons/delete.gif' alt='Delete' /></a>
							</td>	
						</tr>
					<?php endforeach;
					}?>
			<?php endif;?>					
		<?php endforeach;
	}
	?>
</table>
<br /><br />

<div class="hidden" id='dialog-addController' title='<?php echo  $this->translate('Add a controller');?>'>
 <div id='form_controller_error' class="hidden">
	<br />
	<div class='notification_error px300'>
		<div id='form_error_controller_name' class='hidden'><?php echo  $this->translate('You need to set a controller name to validate form.');?></div>		
	</div>
	<br />
 </div>
 <form id='form_controller_add' action='/maerdo/modules/edit/<?php echo $this->module_details['id']?>' method='post'>
 	<br />
	<?php echo  $this->translate('Controller name');?> :
	<br />
	<input type="text" id="controller_name" name="controller_name" />
	<br /><br />
	<?php echo  $this->translate('Description');?> :
	<br />
	<input type="text" name="controller_description" class="px250" />
	<br /><br />
	<input type='hidden' name='form_action' value='add_controller' />
	<input  type='button' onclick='addController()' value='<?php echo  $this->translate('Add');?>' class="px50 fright"/>
	<div class="cleaner"></div>
 </form>
</div>

<div class="hidden" id='dialog-addAction' title='<?php echo  $this->translate('Add an action');?>'>
  <div id='form_action_error' class="hidden">
	<br />
	<div class='notification_error px300'>
		<div id='form_error_action_name' class='hidden'><?php echo  $this->translate('You need to set an action name to validate form.');?></div>		
	</div>
	<br />
 </div>
 <form id='form_action_add' action='/maerdo/modules/edit/<?php echo $this->module_details['id']?> ' method='post'>
 	<br />
	<?php echo  $this->translate('Controller');?> :
	<br />
	<select name='controller_id'>
		<?php foreach($this->module_details['controllers'] as $controller):?>
			<option value='<?php echo $controller['id']?>'><?php echo $controller['name']?></option>
		<?php endforeach;?>
	</select>
	<br /><br />
	<?php echo  $this->translate('Action name');?> :
	<br />
	<input type="text" name="action_name" id='action_name' class="px250" />
	<br /><br />
	<input type='hidden' name='form_action' value='add_action' />
	<input  type='button' onclick='addAction()' value='<?php echo  $this->translate('Add');?>' class="px50 fright"/>
	<div class="cleaner"></div>
 </form>
</div>
