
                    <span class="ul-header"><a id="toggle-pagesnav" href="#" name="toggle-pagesnav"><?php echo $this->translate('Module')?></a></span>
                    <ul id="pagesnav">
                        <li><a class="icn_add_pages" onclick='showModuleForm()' href='#'><?php echo $this->translate('Create a module')?></a></li>                      
                    </ul>

                    <span class="ul-header">Statistics</span>
                    <ul>
						<li>Pages: <?=$this->sidebarCountPage?> </li>
                        <li>Modules: <?=$this->sidebarCountModule?> </li>
                        <li>Controller: <?=$this->sidebarCountController?> </li>
                        <li>Action: <?=$this->sidebarCountAction?> </li>                       
                    </ul>
     