<?php $this->placeholder('sidebar')->captureStart() ?>

                    <span class="ul-header"><a id="toggle-pagesnav" href="#" name="toggle-pagesnav"><?php echo $this->translate('Translate')?></a></span>
                    <ul id="pagesnav">
						<li><a  class="icn_parameters" href='/maerdo/component/translate'><?php echo $this->translate('Configuration')?></a></li>                        
                    </ul>
                    <!-- End Content Nav  -->

                    <span class="ul-header">Statistics</span>
                    <ul>
						<li>Pages: <?=$this->sidebarCountPage?> </li>
                        <li>Modules: <?=$this->sidebarCountModule?> </li>
                        <li>Controller: <?=$this->sidebarCountController?> </li>
                        <li>Action: <?=$this->sidebarCountAction?> </li>                       
                    </ul>
            
<?php $this->placeholder('sidebar')->captureEnd() ?>